Tests fix (#275)
Removed python 3.6, 3.7 from tests

---------

Co-authored-by: Niklas Griessbaum <griessbaum@gmail.com>

diff --git a/.github/workflows/python.yml b/.github/workflows/python.yml
--- a/.github/workflows/python.yml
+++ b/.github/workflows/python.yml
@@ -15,21 +15,24 @@ jobs:
         python-version: [ '3.x', '3.9', '3.10', '3.11' ]
     name: ubuntu-latest Python ${{ matrix.python-version }} 
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
       - name: Install Python 3
-        if: success() || failure()
-        uses: actions/setup-python@v1
+        # if: success() || failure() removed jhrg 5/19/23
+        uses: actions/setup-python@v4
         with:
           python-version: ${{ matrix.python-version }}
       - name: Install dependencies
         if: success() || failure()
         run: |
+          python -m pip install --upgrade pip
           pip3 install -U pip setuptools
-          pip3 install -U "werkzeug<2.1"
+          pip3 install -U "werkzeug>=2.2.2" cryptography
           pip3 install -U numpy webtest gsw coards
           pip3 install -U netCDF4 pytest numpy Webob Jinja2 docopt six beautifulsoup4 requests testresources
       - name: Run tests with pytest
         if: success() || failure()
         run: |
           pip install -e .[tests,netcdf,client]
-          pytest 
+      - name: Run tests with pytest
+        run: |
+          pytest
